basePath: /api/v1
definitions:
  Vo.UserLoginVo:
    properties:
      password:
        description: 密码
        type: string
      token:
        description: token
        type: string
      username:
        description: 名称
        type: string
    required:
    - password
    - username
    type: object
  Vo.UserRegistryVo:
    properties:
      address:
        description: 地址
        type: string
      age:
        description: 年龄
        type: integer
      password:
        description: 密码
        type: string
      phone:
        description: 手机号码
        type: string
      rePassword:
        description: 确认密码
        type: string
      userId:
        description: id
        type: integer
      userName:
        description: 名称
        type: string
    required:
    - password
    - rePassword
    - userName
    type: object
  models.Users:
    properties:
      address:
        description: 地址
        type: string
      age:
        description: 年龄
        type: integer
      id:
        description: 用户id
        type: integer
      password:
        description: 用户密码
        type: string
      phone:
        description: 手机号码
        type: string
      userName:
        description: 用户名称
        type: string
    type: object
  resp.Result:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: leis17@163.com
    name: mark
  description: 一个简单的go web入门项目
  termsOfService: http://swagger.io/terms/
  title: mark-v1 api文档
  version: "1.0"
paths:
  /users/{username}:
    get:
      consumes:
      - multipart/form-data
      description: 根据用户名称，获取用户详情接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 用户姓名
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
      summary: 用户详情接口
      tags:
      - 用户相关接口
  /users/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户登录Vo
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/Vo.UserLoginVo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.Result'
      summary: 用户登录
      tags:
      - 用户相关接口
  /users/registry:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户Vo
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/Vo.UserRegistryVo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.Result'
      summary: 用户注册接口
      tags:
      - 用户相关接口
  /users/userId/{userId}:
    get:
      consumes:
      - multipart/form-data
      description: 根据用户id，获取用户详情接口
      parameters:
      - description: 用户id
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
      summary: 用户详情接口
      tags:
      - 用户相关接口
swagger: "2.0"
